"""Trading signal entities — output from agent analysis pipeline.

Ref: Doc 04 §1.6
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal
from enum import StrEnum

from core.value_objects import Price, Symbol


class SignalStrength(StrEnum):
    """Signal confidence level."""

    STRONG_BUY = "STRONG_BUY"
    BUY = "BUY"
    NEUTRAL = "NEUTRAL"
    SELL = "SELL"
    STRONG_SELL = "STRONG_SELL"


class AgentSource(StrEnum):
    """Which agent produced this signal."""

    SCREENER = "SCREENER"
    TECHNICAL = "TECHNICAL"
    FUNDAMENTAL = "FUNDAMENTAL"
    RISK = "RISK"
    SUPERVISOR = "SUPERVISOR"


@dataclass(frozen=True, slots=True)
class TradingSignal:
    """A trading signal produced by an agent.

    ★ Immutable — signals are facts, not mutable state.
    ★ Contains full provenance: who produced it, when, why.
    """

    signal_id: str
    symbol: Symbol
    strength: SignalStrength
    source: AgentSource
    target_price: Price | None
    stop_loss: Price | None
    confidence: Decimal  # 0.0 to 1.0
    reasoning: str  # Human-readable explanation
    created_at: datetime


@dataclass(frozen=True, slots=True)
class AIInsight:
    """Structured AI analysis result — from LLM/NPU inference.

    ★ Generated by Fundamental Agent using OpenVINO NPU.
    ★ Contains both the raw analysis and structured data.
    """

    symbol: Symbol
    summary: str  # 1-2 sentence summary
    sentiment: SignalStrength  # Bullish/Bearish/Neutral mapping
    key_factors: tuple[str, ...]  # Top factors influencing the analysis
    confidence: Decimal
    model_name: str  # e.g. "phi-3-mini-int4"
    inference_time_ms: float  # NPU inference latency
    created_at: datetime
